baseURL = "https://gedankensplitter.netlify.app/"
title = "Lukas Beer"
theme = "PaperMod"
languageCode = "de-DE"

[pagination]
pagerSize = 5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  homeInfoParams = { Title = "Willkommen in meiner digitalen Sammlung.", Content = "Notizen, Gedanken, Zusammenfassungen, Zitate, ... ohne Anspruch auf Vollständigkeit und Perfektion. Mehr über mich findest du [hier] ({{% ref "/about/" %}})." }
  ShowReadingTime = true
  ShowShareButtons = false
  ShowToc = true
  ShowBreadCrumbs = true
  dateFormat = "2.1.2006"

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "archive"
    name = "Archiv"
    url = "/archives/"
    weight = 12
  [[menu.main]]
    identifier = "about"
    name = "Über mich"
    url = "/about/"
    weight = 20
  [[menu.main]]
    identifier = "search"
    name = "Suche"
    url = "/search/"
    weight = 30
