baseURL = "https://gedankensplitter.netlify.app/"
title = "Lukas' GedankenSplitter"
theme = "PaperMod"
languageCode = "de-DE"

[pagination]
pagerSize = 5


[params]
  homeInfoParams = { Title = "Willkommen in meiner digitalen Sammlung.", Content = "Notizen, Gedanken, Zusammenfassungen, Zitate, ... ohne Anspruch auf Vollständigkeit und Perfektion." }
  ShowReadingTime = true
  ShowShareButtons = false
  ShowToc = true
  ShowBreadCrumbs = true
  dateFormat = "2.1.2006"

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/archives/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "Über mich"
    url = "/about/"
    weight = 20
