baseURL = "https://lukasbeer.ch/"
title = "Lukas Beer"
theme = "PaperMod"
defaultContentLanguage = "de"
languageCode = "de-DE"
buildDrafts = true

[pagination]
pagerSize = 5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  homeInfoParams = { Title = "Willkommen in meinem digitalen Notizbuch.", Content = "Hier schreibe ich für mich - eine lose, unvollständige Sammlung aus Ideen, Projekten und Inspirationen – seis über Pädagogik, Technik, Familie, Bücher, ... Stöbere mit, wenn du magst!" }
  ShowReadingTime = true
  ShowShareButtons = false
  ShowToc = true
  ShowBreadCrumbs = true
  dateFormat = "2.1.2006"

[menu]
  [[menu.main]]
    identifier = "archive"
    name = "Archiv"
    url = "/archives/"
    weight = 12
  [[menu.main]]
    identifier = "drafts"
    name = "Entwürfe"
    url = "/drafts/"
    weight = 10
  [[menu.main]]
    identifier = "search"
    name = "Suche"
    url = "/search/"
    weight = 30
